package com.ahoy.entities.custom_views_status

enum class CustomFormsStatus {
    DYNAMIC,
    CHANGE_EMPLOYEE_STATUS,
    EMPLOYEE_IMPROVEMENT_PLAN,
    TRANSFER_REQUEST,
    LEAVES,
    ROTATION_REQUEST,
    INSTALLMENT_PLAN,
    FORMAL_PROCEDURE,
    INTERNAL_SECONDMENT,
    GRIEVANCE_AND_COMPLAINS,
    TRANSFER_REQUEST_BASED_ON_BUSINESS_NEED,
    TRANSFER_REQUEST_INTERNAL_RECRUITMENT,
    AUTOMATING_JOB_INTERVIEWS_FORM,
    TRANSFER_REQUEST_FOR_SPECIAL_CIRCUMSTANCES_FORM,
    STARTING_WORK_CONFIRMATION,
    IAM_USER_TERMINATE_ACCOUNT,
    IAM_UPDATE_USER_INFO,
    EXTEND_EXPIRE_DATE,
    COOPERATE_PERFORMANCE,
    EDUCATION_ALLOWANCE,
    PROFESSIONAL_CERTIFICATE
}